image:
  repository: registry.ustpace.com/docker-sandbox/demo-project-micro-service-2
  tag: latest
  pullPolicy: Always
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx-internal
  hosts:
  - host: demo-project-micro-service-2-dev.dagility.com
    paths:
    - /
serviceAccount:
  create: false
